name: deploy

on:
  push:
    branches:
      - master

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull images
        run: |
          for image in $(cat repos.txt); do
              printf "Pulling $image\n";
              docker pull "${image}"
          done
