name: deploy

on:
  pull_request: []
  push:
    branches:
      - master

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull images
        run: |
          lastseen=""
          for image in $(cat repos.txt); do
             # Parse repository name, we will remove the previous image if different
             readarray -d : -t repository <<< "$image"
             if [ "${lastseen}" != "" ] && [ "${repository[0]}" != "${lastseen}" ]; then
                 printf "Removing image ${lastseen} to make room."
                 docker rmi "${lastseen}"
             fi
             lastseen="${repository[0]}"
             printf "Pulling $image\n";
             docker pull "${image}"
          done
